name: CI/CD - CBC_API_REST

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.2
        env:
          MYSQL_DATABASE: cbc_api
          MYSQL_USER: admin
          MYSQL_PASSWORD: 123
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -u root -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - name: Clonar o repositório
      uses: actions/checkout@v4

    - name: Verificar sintaxe do PHP
      run: php -l index.php

    - name: Subir containers (docker-compose)
      run: docker compose up -d --build

    - name: Aguardar containers subirem
      run: sleep 15

    - name: Testar resposta do servidor
      run: |
        curl --fail http://localhost:8080 || (echo "Erro: API não respondeu" && exit 1)

    - name: Finalizar containers
      if: always()
      run: docker compose down -v